title: Lebanon Zoning Ordinance
description: A static interface for the City of Lebanon's zoning regulations.
theme: minima
show_excerpts: false
paginate: false

header_pages:
  - index.md
  - ordinance.md
